#!/usr/bin/env bash
# This script is displaying "all processes"


echo "List of currently running processes:"

# Using the ps command to display process information
ps axjf

# Note: The "j" option displays the process hierarchy in a tree format.

