#!/usr/bin/env bash

# Functions
start_my_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "manage_my_process is already running."
    else
        /bin/bash /path/to/manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started."
    fi
}

stop_my_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        echo "manage_my_process stopped."
    else
        echo "manage_my_process is not running."
    fi
}

restart_my_process() {
    stop_my_process
    start_my_process
    echo "manage_my_process restarted."
}

# Main
case "$1" in
    start)
        start_my_process
        ;;
    stop)
        stop_my_process
        ;;
    restart)
        restart_my_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

