#!/usr/bin/env bash
# This script is displaying "Beheaded process PID"

if [ -z "$PID" ]; then
  echo "Process '7-highlander' is not running."
else
  echo "Stopping process '7-highlander' with PID $PID"

  kill -15 "$PID"
fi

