#!/usr/bin/env bash

# Update the system's package lists
sudo apt-get update

# Install the necessary packages
sudo apt-get install -y dnsmasq

# Configure the local DNS server
echo "address=/localhost/127.0.0.2" | sudo tee /etc/dnsmasq.d/localhost.conf
echo "address=/facebook.com/8.8.8.8" | sudo tee /etc/dnsmasq.d/facebook.conf

# Restart the DNS server
sudo systemctl restart dnsmasq


