#!/usr/bin/env bash

# Server details
user="ubuntu"
hostname="52.91.127.195"

# Path to the private key
private_key="~/.ssh/school"

# SSH command with single-character flags
ssh -i "$private_key" "$user@$hostname"

